networks:
  frontend-network:
    driver: bridge
  
  backend-network:
    driver: bridge

volumes:
  mongodb:
    driver: local

services:

  frontend:
    build: ./src/frontend
    image: mern-frontend:v1
    container_name: mern-frontend
    ports:
      - "8081:80"
    networks:
      - frontend-network
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./src/backend
    image: mern-backend:v1
    container_name: mern-backend
    ports:
      - "5050:5050"
    networks:
      - frontend-network
      - backend-network
    environment:
      - PORT=5050
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend-network
    volumes:
      - mongodb:/data/db
    restart: unless-stopped

